tools:
  test:
    enabled: true
    num_tests: 3
    testing_framework: jest
  review:
    enabled: true
  describe:
    enabled: true
  improve:
    enabled: true
git:
  auto_commit_changes: true
  auto_commit_prefix: "[pr-agent] "